# Generated by Django 4.0.1 on 2022-04-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWIE', '0009_inputulap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputRGHS',
            new_name='InputEnhance',
        ),
        migrations.RenameModel(
            old_name='InputMIP',
            new_name='InputRestore',
        ),
        migrations.DeleteModel(
            name='InputCLAHE',
        ),
        migrations.DeleteModel(
            name='InputDCP',
        ),
        migrations.DeleteModel(
            name='InputRAY',
        ),
        migrations.DeleteModel(
            name='InputULAP',
        ),
    ]
